# makefile -- Build doscalls.lib

# tools
#       masm.exe -- IBM Macro Assembler/2 Version 1.00
#       lib.exe  -- IBM Library Manager/2 Version 1.00 
#       maketc.exe -- GNU MAKE 3.71

.SUFFIXES:
.SUFFIXES: .asm .obj .lib

AS = masm.exe
ASFLAGS = 
LIB = lib.exe

ASMS = console.asm datetime.asm device.asm dir.asm disk.asm \
      file.asm filelib.asm memory.asm misc.asm process.asm \
      getenvs.asm getargs.asm    
OBJS = console.obj datetime.obj device.obj dir.obj disk.obj \
      file.obj filelib.obj memory.obj misc.obj process.obj \
      getenvs.obj getargs.obj    
INCS = console.mac datetime.mac device.mac dir.mac disk.mac \
      file.mac filelib.mac memory.mac misc.mac process.mac \
      getenvs.mac getargs.mac constant.inc      

all : doscalls.lib

doscalls.lib : $(OBJS)

%.obj : %.asm
	$(AS) $(ASFLAGS) $(basename $<);
	$(LIB) doscalls.lib -+$(basename $@),doscalls.cat;
	-rm doscalls.bak

.PHONY : clean

clean :
	-rm *.obj
	-rm doscalls.cat
	-rm doscalls.lib
